### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/Mini-agi-AI#4]
The codebase encounters critical issues due to unresolved dependencies, which are not documented. This makes installation challenging and leads to errors during function execution. We need to identify and resolve these missing dependencies. Additionally, clear instructions on how to install the necessary dependencies should be provided in the documentation to ensure smooth setup and operation.

**Comment by Muhammad-Awab** [comment]
The issue was resolved by identifying the missing dependencies and adding them to the build.config file. Updated the documentation with specific installation steps: npm install --config build.config. The code is now executing without errors, and all functions are working correctly. Please update your local environment by pulling the latest changes and following the revised installation instructions.
